title: "Zcon Docs"
description: "Documentation for Zcon Projects"
theme: "just-the-docs"  # 테마 설정

# GitHub Pages URL 설정
baseurl: "/zcon-docs"  # repository 이름
url: "https://your-username.github.io"  # 사용자명에 맞게 수정

# 사이드바 네비게이션 설정
just_the_docs:
  # 사이드바 계층 구조를 설정합니다.
  nav_order: 1
  sidebar:
    - title: "Home"
      url: "/"
      nav_order: 1
    - title: "Cloud Migration"
      url: "/cloud migration/"
      nav_order: 2
    - title: "Backup & DR"
      url: "/backup & DR/"
      nav_order: 3
    - title: "FAQ"
      url: "/faq/"
      nav_order: 4

